name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
jobs:
  build:
    name: build_and_deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      # - name: Install dependencies
      #   run: yarn install

      - name: Generate
        run: yarn generate

      - name: Deploy
        run: yarn deploy:prod
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
